server:
  port: 9999
spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/demorego
    username: postgres
    password: janara2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: satkynovaz@gmail.com
    password: janara2004
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true